{% set name = "GlabTop2-py" %}
{% set version = "2.1.0" %}
{% set sha256 = "c5b73e5768af1072d21862721fb07ecb3126b5e6a36a6dac2931c99bc77c6c3b" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # If getting the source from GitHub remove the line above
  # uncomment the line below and modify as needed
  # url: https://github.com/simplejson/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # Uncomment the following line if the package is pure python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/meta.html#building-noarch-packages for more details.
  noarch: python
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  channels:
    - conda-forge
    - WilcoTerink
    - defaults
  build:
    - python
    - setuptools
  run:
    - python >=3.11
    - pandas
    - numpy
    - geopandas
    - scipy
    - pcraster
    - streamlit

test:
  imports:
    - pcraster
    - GlabTop2
#  commands:
#    - python -m GlabTop2.main

about:
  home: https://github.com/WilcoTerink/GlabTop2-py
  license: GNU General Public License v3 (GPL-3.0)
  license_family: GPL
  summary: GlabTop2 (Glacier bed Topography) model
  description: "Repository for the GlabTop2 model\r\n=============================================================\r\n\r\nThe documentation can be found here: https://glabtop2-py.readthedocs.io/en/latest/.\r\
    \n"
  doc_url: ''
  dev_url: ''
